inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - '**/extconf.rb'
  TargetRubyVersion: 2.6

# Layout/RescueEnsureAlignment: { Enabled: false } # with extreme prejudice
# Style/FrozenStringLiteralComment: { Enabled: false }
# Style/RegexpLiteral: { Enabled: false } # allow using %r{} for regexes
# Lint/MissingSuper: { Enabled: false }
